"""empty message

Revision ID: 1bb4890526b
Revises: 3feceb7535f
Create Date: 2016-08-08 22:40:12.280000

"""

# revision identifiers, used by Alembic.
revision = '1bb4890526b'
down_revision = '3feceb7535f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
