"""empty message

Revision ID: 39316d1cd4a8
Revises: 5643d7cbcebd
Create Date: 2016-08-11 12:05:51.384000

"""

# revision identifiers, used by Alembic.
revision = '39316d1cd4a8'
down_revision = '5643d7cbcebd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avarda_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avarda_hash')
    ### end Alembic commands ###
