"""empty message

Revision ID: 3b38be6edbbe
Revises: 1f2196fe50fd
Create Date: 2016-08-12 17:35:11.493000

"""

# revision identifiers, used by Alembic.
revision = '3b38be6edbbe'
down_revision = '1f2196fe50fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
